version: "3"
services:
  book-service:
    build: book-service/.
    ports:
      - "9090:9090"
  order-service:
    build: book-service/.
    ports:
      - "9091:9091"
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: authservice