version: "3"
services:
  auth-service:
    build: auth-service/.
    networks:
      - getir-network
    depends_on:
      - mongo
    ports:
      - "9092:9092"
  mongo:
    image: mongo
    networks:
      - getir-network
    ports:
      - "27017:27017"

networks:
  getir-network: