version: "3"
services:
  api-gateway:
    build: api-gateway/.
    networks:
      - getir-network
    ports:
      - "8080:8080"
  order-service:
    build: order-service/.
    depends_on:
      - auth-service
      - book-service
    networks:
      - getir-network
  book-service:
    build: book-service/.
    depends_on:
      - auth-service
    networks:
      - getir-network
  auth-service:
    build: auth-service/.
    networks:
      - getir-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    networks:
      - getir-network

networks:
  getir-network: