version: "3"
services:
  order-service:
    build: order-service/.
    depends_on:
      - auth-service
      - book-service
    networks:
      - getir-network
    ports:
      - "9091:9091"
  book-service:
    build: book-service/.
    depends_on:
      - auth-service
    networks:
      - getir-network
    ports:
      - "9090:9090"
  auth-service:
    build: auth-service/.
    networks:
      - getir-network
    depends_on:
      - mongo
    ports:
      - "9092:9092"
  mongo:
    image: mongo
    networks:
      - getir-network
    ports:
      - "27017:27017"

networks:
  getir-network: