zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    book:
      path: /api/book/**
      url: http://book-service:8080/
      stripPrefix: true
    order:
      path: /api/order/**
      url: http://order-service:8080/
      stripPrefix: true
    auth:
      path: /api/auth/**
      url: http://auth-service:8080/
      stripPrefix: true
