INSERT INTO BOOK (ID, NAME, PAGE_SIZE, PRICE, STOCK)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'Fareler ve İnsanlar', 150, 10, 150);

INSERT INTO BOOK (ID, NAME, PAGE_SIZE, PRICE, STOCK)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'İhanet Noktası', 450, 25, 20);

INSERT INTO BOOK (ID, NAME, PAGE_SIZE, PRICE, STOCK)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'Amok Koşucusu', 110, 3, 1000);

INSERT INTO BOOK (ID, NAME, PAGE_SIZE, PRICE, STOCK)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'Yeraltından Notlar', 250, 10, 300);

INSERT INTO BOOK (ID, NAME, PAGE_SIZE, PRICE, STOCK)
VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'Altıncı Koğuş', 200, 8, 500);